language: node_js
before_install:
- openssl aes-256-cbc -k "12345678" -in se234.pem.enc -out se234.pem -d
- sudo chmod 400 se234.pem
install: true
script: true
after_success:
- ls -l
- scp -i "se234.pem" -r html/* ubuntu@54.255.174.42:/var/www/html/
env:
  global:
    secure: FIxqBaRTVdcDfRgBjlz97/Hv1guGRTgekPUcfU09fq5HbGvhWPe1uuecboxFR87EG6htiip9/IAKAEsab/60GpaGUXWCkv68vgexax0O0oogmctsCFxeo/eY8Y0ejpb3msc4I6U14tMY4saC2w2IKwQegXBbE7FRgnD5z9Qu7F8pg/43QVtUlf/RRV0lwe1MkoQzIxRlZFX2YnAy2kXzZzedCwhwgcUYP8yS6q770vc6TxHt9H87i7kwegYJs9qhvE1ezG5F4ODrupYrjdI2+HRy7LmxFBwIjp0RcyXKtoUjh39PtJCe57CedmuRfIvFz//hKnwwUo1AlX+eRi6qgNAz9nCQXF2q7TbMQhU8JgcbSRF+TDib4rpZAQjQuyjWYR1Y8NefE+S1ia/EQX1vuAYguFsusdqMuUDxMvDcQGyyml+uRu4QxWvhzk8FYaj8hjboL0GClv6JSWlouhG6+JYnm5aJssUAZXp52zJ0WaKBUoYWaNVhdHnKmhk/iqtpXX3R4pxWVfpPHdUR/N+03JXl9E2IkKMFWDVQHL7NQuOYLya5McKWusmR802+D8GZ3WOhEt5SiyPi+JdtkHJlyFsv4O1Im//fzXRk80dSjYKH3Pw9l8f2gLww07oE5bkI3NFqywlEN7LppstrldKdRHgBlrrFqHlHH+0fwiyqzQE=
addons:
  ssh_known_hosts:
  - 54.255.174.42