language: node_js
before_install:
- openssl aes-256-cbc -k "12345678" -in se234.pem.enc -out se234.pem -d
- sudo chmod 400 se234.pem
install: true
script: true
after_success:
- ls -l
- scp -i "se234.pem" -r html/* ubuntu@54.255.174.42:/var/www/html/
env:
  global:
  - secure: Ji4VMY5Khb5WRzcgIDq+TBLgcd0Pe6sTbBGS19qMT4aZfKKqKyuku0HN6JC6ihad1+BVhgRZ7wN5lMd+vg9JsA8q5LMCwvxSBR9eI/Ral+Sn0ya8S7rsBiXEpSU7bpwp21XtAmPDari8N9nolPFuBEkCPe16dfi2uWmJFr5rCb3I04jVZjfby0RJhtdEIZiiKEjVK/9K7UwwTxXExn6TH6O0aSevlpyRjEy62Puy38vcZGSIoIhGGoA/DeagjTp9vfeK60W8wcTzuikS/2dYL2LSLTbWMiKtK9d7ps6bfV2kJ557eJp0RQQFl0qkCeC64vBRiA1IbGEuXdrFHQ01dEzjcmSgFn1NnG8l9r2eYAuC9bBjWmnCtBCEkGHvNYa9MTqsLIUDPvMuvtP9hCSO44UX1MDm5wWa9tKZhS1azFjafwz1DUKUPdwpw2I5Rs+i2wZMDu8mWlNWaGtbN4sj6f5b76yDcS4CMIGFWRY+IvVrvxNciEP6ScgsUaEVCbPe2uz3B2Q/rNqjmFcXDGmUEYOuL5LY/inJYscb84zlQUuH4uPX/P40g05iaHoCNKVWHz7VNKun0eC/k5k57AXStXxJvKEr/rRbRRGLGanPEVt6f2t5f8e1YU4UWDJRGFZzD72jTtzAkNW1lKKPQLmTw3QrGJ5QdJM3R1NtdZytsRw=
addons:
  ssh_known_hosts:
  - 54.255.174.42
