language: node_js
before_install:
- openssl aes-256-cbc -k "$super_secret_password" -in se234.pem.enc -out se234.pem
  -d
- sudo chmod 400 se234.pem
install: true
script: true
after_success:
- ls -l
- scp -i "se234.pem" -r html/* ubuntu@54.255.174.42:/var/www/html/
env:
  global:
    secure: IqZ7cAJdCnLuzjMDcNk+kdB3EUlc92wWlxNyWVvUfi/wZ9wEu766fPoxMQtY+Ebnu7NKIIxvDQmWDa0EjHSK6d4C5/B0FQl+1QekW9ijaxclqIA3TnLG27TBzp7vqmTJxbb9C0UdnZji49W4BukzO7tAIwR4kRMBP9bqhjbHRswZw/vQRp/cl5umhlX6OKAghOb4zdX6fIExtBTeADEJlPHpGj9MJmhuATbIlUEPpK4scIeXVuqdJ2Of0RWWe15p1Dyn9y39XaHYGOTMDUCE1tcxvmoNbBh+Kg9Eq42kxEyaUSWavNKMyBkHdGwLWZqqnXrey86cUYyWy1UqqQziqmA24NuvuDRTr92sKLc6Z+e+3pkHSNHpaDgHsCqDYcNIn5jKmRVPt9GgeEOBb4yprans6D5SK23tocIDs7h5cSmAagO+4pEjovuQlJh5xgTnOgCSkwb4j8s90IR1WyuJDe2ho30YqaPsocwlXAg81dtxcdLp7mkZM1MUFDSh35sqtv/mPzKrRqWoYe2plJmWPJ6jNxTVrqZhH+i+UwttdQQpDTyWa/Q8d1lLJtoukkF7r1WQerTWnwNL6BnC9uE19DLwAi0pNHgTsC6KpEvAvL3mblQTFpBCO4m1MeUZaFUjv2kNr7hn0gLQNMGJeAKqhdURDWLqDxX1KJLEVGurB3c=
addons:
  ssh_known_hosts:
  - 54.255.174.42